# Generated by Django 4.2.11 on 2024-05-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_yoyaku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoyaku_id',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
