# Generated by Django 4.2.11 on 2024-05-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_yoyaku_id_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank_is_free',
            field=models.BooleanField(default=True, help_text='無料会員ならTrue、デフォルトは無料会員', verbose_name='rank'),
        ),
    ]
