# Generated by Django 4.2.11 on 2024-05-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_rank_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoyaku_id',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
