# Generated by Django 4.2.11 on 2024-05-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('accounts', '0007_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_shop',
            field=models.ManyToManyField(blank=True, to='shops.shop', verbose_name='favorite_shop'),
        ),
    ]
