# Generated by Django 4.2.11 on 2024-05-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('accounts', '0008_user_favorite_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_shop',
            field=models.ManyToManyField(blank=True, related_name='related_favorite_shop', to='shops.shop', verbose_name='favorite_shop'),
        ),
    ]
