# Generated by Django 4.2.11 on 2024-05-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('accounts', '0009_alter_user_favorite_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_review_shop', to='shops.shop', verbose_name='review_shop'),
        ),
    ]
