# Generated by Django 4.2.11 on 2024-05-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_review_shop_alter_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopreview',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default='3', verbose_name='score'),
        ),
    ]
