# Generated by Django 4.2.11 on 2024-05-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('accounts', '0012_shopreview_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopreview',
            unique_together={('shop_id', 'user_id')},
        ),
    ]
