# Generated by Django 4.2.11 on 2024-09-25 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_shop_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiyaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiyakuName', models.CharField(max_length=10, unique=True, verbose_name='規約名称')),
                ('kiyakuContent', models.TextField(blank=True, verbose_name='規約内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新時間')),
                ('lastUpdater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_update_user', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
        ),
    ]
