# Generated by Django 4.2.11 on 2024-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_transaction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
