# Generated by Django 4.2.11 on 2024-09-28 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0004_alter_transaction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_accounts_email', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='accounts_email'),
        ),
    ]
