# Generated by Django 4.2.11 on 2024-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_transaction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
