# Generated by Django 4.2.11 on 2024-11-05 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0006_alter_transaction_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_id'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Userオブジェクトとの紐づき用'),
        ),
    ]
