# Generated by Django 4.2.11 on 2024-05-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='yoyaku_id',
            field=models.TextField(max_length=255, null=True, verbose_name='予約ID'),
        ),
    ]
