# Generated by Django 4.2.11 on 2024-08-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='numbers',
            field=models.IntegerField(default=1, verbose_name='予約人数'),
        ),
    ]
