# Generated by Django 4.2.11 on 2024-10-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.CharField(blank=True, default='yyyy-mm-dd HH:MM:SS', max_length=255, null=True, verbose_name='終了時間だが設定不要'),
        ),
    ]
