# Generated by Django 4.2.11 on 2024-10-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_schedule_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateField(blank=True, default='2024-01-01 01:01:01', max_length=255, null=True, verbose_name='終了時間だが設定不要'),
        ),
    ]
