# Generated by Django 4.2.11 on 2024-11-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_schedule_start_schedule_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='startHor',
            new_name='startHour',
        ),
    ]
