# Generated by Django 4.2.11 on 2024-11-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_rename_starthor_schedule_starthour'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='エラー回避用'),
        ),
    ]
