# Generated by Django 4.2.11 on 2024-09-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_reviewstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewComment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='reviewComment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
