# Generated by Django 4.2.11 on 2024-11-01 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_shop_endhour1_alter_shop_endhour2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_alter_review_reviewcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewComment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewShopName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_reviewShopName', to='shops.shop', verbose_name='レビュー対象の店舗名'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewStar',
            field=models.CharField(blank=True, choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=20, verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewUserName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_reviewUserName', to=settings.AUTH_USER_MODEL, verbose_name='レビューしたユーザー名'),
        ),
    ]
