# Generated by Django 4.2.11 on 2024-04-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('addressLat', models.FloatField(blank=True, null=True)),
                ('addressLng', models.FloatField(blank=True, null=True)),
                ('startHour', models.TimeField(blank=True, null=True)),
                ('endHour', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('regularHoliday', models.TextField(blank=True, null=True)),
                ('ShopTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shoptag')),
            ],
        ),
    ]
