# Generated by Django 4.2.11 on 2024-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='ShopTag',
        ),
        migrations.AlterField(
            model_name='shop',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='ShopTag',
            field=models.ManyToManyField(blank=True, to='shops.shoptag'),
        ),
    ]
