# Generated by Django 4.2.11 on 2024-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_shop_shoptag_alter_shop_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='endHour',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='startHour',
        ),
        migrations.AddField(
            model_name='shop',
            name='endHour1',
            field=models.TimeField(blank=True, null=True, verbose_name='昼営業時間'),
        ),
        migrations.AddField(
            model_name='shop',
            name='endHour2',
            field=models.TimeField(blank=True, null=True, verbose_name='夜営業時間'),
        ),
        migrations.AddField(
            model_name='shop',
            name='startHour1',
            field=models.TimeField(blank=True, null=True, verbose_name='昼営業時間'),
        ),
        migrations.AddField(
            model_name='shop',
            name='startHour2',
            field=models.TimeField(blank=True, null=True, verbose_name='夜営業時間'),
        ),
    ]
