# Generated by Django 4.2.11 on 2024-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_shop_endhour_remove_shop_starthour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', '月曜日'), ('Tue', '火曜日'), ('Wed', '水曜日'), ('Thu', '木曜日'), ('Fri', '金曜日'), ('Sat', '土曜日'), ('Sun', '日曜日')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='regularHoliday',
        ),
        migrations.AddField(
            model_name='shop',
            name='regularHoliday',
            field=models.ManyToManyField(blank=True, to='shops.regularholiday', verbose_name='定休日（無入力で定休日無し）'),
        ),
    ]
