# Generated by Django 4.2.11 on 2024-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_regularholiday_remove_shop_regularholiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='regularHoliday',
        ),
        migrations.AddField(
            model_name='shop',
            name='regularHoliday',
            field=models.CharField(blank=True, choices=[('All', '定休日無し'), ('Mon', '月曜日'), ('Tue', '火曜日'), ('Wed', '水曜日'), ('Thu', '木曜日'), ('Fri', '金曜日'), ('Sat', '土曜日'), ('Sun', '日曜日')], max_length=3, verbose_name='定休日（無入力で定休日無し）'),
        ),
    ]
