# Generated by Django 4.2.11 on 2024-10-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_shop_regularholiday_shop_regularholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='regularHoliday',
            field=models.CharField(blank=True, choices=[('All', '定休日無し'), ('1', '月曜日'), ('2', '火曜日'), ('3', '水曜日'), ('4', '木曜日'), ('5', '金曜日'), ('6', '土曜日'), ('0', '日曜日')], max_length=3, verbose_name='定休日（無入力で定休日無し）'),
        ),
    ]
