# Generated by Django 4.2.11 on 2024-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shop_regularholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='review',
        ),
        migrations.AlterField(
            model_name='shop',
            name='ShopTag',
            field=models.ManyToManyField(blank=True, to='shops.shoptag', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='addressLat',
            field=models.FloatField(blank=True, null=True, verbose_name='住所緯度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='addressLng',
            field=models.FloatField(blank=True, null=True, verbose_name='住所経度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='店外観写真'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='店舗紹介文'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(max_length=20, verbose_name='店名'),
        ),
    ]
