# Generated by Django 4.2.11 on 2024-11-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_remove_shop_review_alter_shop_shoptag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='endHour1',
            field=models.TimeField(blank=True, null=True, verbose_name='昼営業終了時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='endHour2',
            field=models.TimeField(blank=True, null=True, verbose_name='夜営業終了時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='startHour1',
            field=models.TimeField(blank=True, null=True, verbose_name='昼営業開始時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='startHour2',
            field=models.TimeField(blank=True, null=True, verbose_name='夜営業開始時間'),
        ),
    ]
