# Generated by Django 4.2.11 on 2024-11-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_reviewcomment_and_more'),
        ('shops', '0009_alter_shop_endhour1_alter_shop_endhour2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='review',
            field=models.ManyToManyField(blank=True, to='review.review', verbose_name='店舗レビュー'),
        ),
    ]
