# Generated by Django 4.2.11 on 2024-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_shop_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_binary',
            field=models.TextField(blank=True, null=True, verbose_name='本番環境用設定'),
        ),
    ]
