# Generated by Django 4.2.11 on 2024-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_shop_image_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image_binary',
            field=models.BinaryField(blank=True, null=True, verbose_name='本番環境用設定'),
        ),
    ]
