# Generated by Django 4.2.11 on 2024-11-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_shop_image_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image_binary',
        ),
    ]
